language: java

dist: trusty

jdk:
- openjdk8

install: /bin/true

branches:
  only:
  - master

script:
- cd code
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
- mvn test verify --batch-mode
